export const PEDIDO_CRIAR_REQUEST = 'PEDIDO_CRIAR_REQUEST'
export const PEDIDO_CRIAR_SUCCESS = 'PEDIDO_CRIAR_SUCCESS'
export const PEDIDO_CRIAR_FAIL = 'PEDIDO_CRIAR_FAIL'
export const PEDIDO_CRIAR_RESET = 'PEDIDO_CRIAR_RESET'

export const PEDIDO_DETALHES_REQUEST = 'PEDIDO_DETALHES_REQUEST'
export const PEDIDO_DETALHES_SUCCESS = 'PEDIDO_DETALHES_SUCCESS'
export const PEDIDO_DETALHES_FAIL = 'PEDIDO_DETALHES_FAIL'

export const PEDIDO_PAGAR_REQUEST = 'PEDIDO_PAGAR_REQUEST'
export const PEDIDO_PAGAR_SUCCESS = 'PEDIDO_PAGAR_SUCCESS'
export const PEDIDO_PAGAR_FAIL = 'PEDIDO_PAGAR_FAIL'
export const PEDIDO_PAGAR_RESET = 'PEDIDO_PAGAR_RESET'

export const PEDIDO_LISTAR_PEDIDOS_REQUEST = 'PEDIDO_LISTAR_PEDIDOS_REQUEST'
export const PEDIDO_LISTAR_PEDIDOS_SUCCESS = 'PEDIDO_LISTAR_PEDIDOS_SUCCESS'
export const PEDIDO_LISTAR_PEDIDOS_FAIL = 'PEDIDO_LISTAR_PEDIDOS_FAIL'
export const PEDIDO_LISTAR_PEDIDOS_RESET = 'PEDIDO_LISTAR_PEDIDOS_RESET'

