export const PRODUTO_LISTA_REQUEST = 'PRODUTO_LISTA_REQUEST'
export const PRODUTO_LISTA_SUCCESS = 'PRODUTO_LISTA_SUCCESS'
export const PRODUTO_LISTA_FAIL = 'PRODUTO_LISTA_FAIL'

export const PRODUTO_DETALHES_REQUEST = 'PRODUTO_DETALHES_REQUEST'
export const PRODUTO_DETALHES_SUCCESS = 'PRODUTO_DETALHES_SUCCESS'
export const PRODUTO_DETALHES_FAIL = 'PRODUTO_DETALHES_FAIL'