export const PRODUTO_LISTA_REQUEST = 'PRODUTO_LISTA_REQUEST'
export const PRODUTO_LISTA_SUCCESS = 'PRODUTO_LISTA_SUCCESS'
export const PRODUTO_LISTA_FAIL = 'PRODUTO_LISTA_FAIL'

export const PRODUTO_DETALHES_REQUEST = 'PRODUTO_DETALHES_REQUEST'
export const PRODUTO_DETALHES_SUCCESS = 'PRODUTO_DETALHES_SUCCESS'
export const PRODUTO_DETALHES_FAIL = 'PRODUTO_DETALHES_FAIL'

export const PRODUTO_APAGAR_REQUEST = 'PRODUTO_APAGAR_REQUEST'
export const PRODUTO_APAGAR_SUCCESS = 'PRODUTO_APAGAR_SUCCESS'
export const PRODUTO_APAGAR_FAIL = 'PRODUTO_APAGAR_FAIL'

export const PRODUTO_CRIAR_REQUEST = 'PRODUTO_CRIAR_REQUEST'
export const PRODUTO_CRIAR_SUCCESS = 'PRODUTO_CRIAR_SUCCESS'
export const PRODUTO_CRIAR_FAIL = 'PRODUTO_CRIAR_FAIL'
export const PRODUTO_CRIAR_RESET = 'PRODUTO_CRIAR_RESET'

export const PRODUTO_ATUALIZAR_REQUEST = 'PRODUTO_ATUALIZAR_REQUEST'
export const PRODUTO_ATUALIZAR_SUCCESS = 'PRODUTO_ATUALIZAR_SUCCESS'
export const PRODUTO_ATUALIZAR_FAIL = 'PRODUTO_ATUALIZAR_FAIL'
export const PRODUTO_ATUALIZAR_RESET = 'PRODUTO_ATUALIZAR_RESET'