export const USUARIO_LOGIN_REQUEST = 'USUARIO_LOGIN_REQUEST'
export const USUARIO_LOGIN_SUCCESS = 'USUARIO_LOGIN_SUCCESS'
export const USUARIO_LOGIN_FAIL = 'USUARIO_LOGIN_FAIL'

export const USUARIO_LOGOUT = 'USUARIO_LOGOUT'

export const USUARIO_REGISTRO_REQUEST = 'USUARIO_REGISTRO_REQUEST'
export const USUARIO_REGISTRO_SUCCESS = 'USUARIO_REGISTRO_SUCCESS'
export const USUARIO_REGISTRO_FAIL = 'USUARIO_REGISTRO_FAIL'

export const USUARIO_DETALHES_REQUEST = 'USUARIO_DETALHES_REQUEST'
export const USUARIO_DETALHES_SUCCESS = 'USUARIO_DETALHES_SUCCESS'
export const USUARIO_DETALHES_FAIL = 'USUARIO_DETALHES_FAIL'
export const USUARIO_DETALHES_RESET = 'USUARIO_DETALHES_RESET'


export const USUARIO_ATUALIZA_PERFIL_REQUEST = 'USUARIO_ATUALIZA_PERFIL_REQUEST'
export const USUARIO_ATUALIZA_PERFIL_SUCCESS = 'USUARIO_ATUALIZA_PERFIL_SUCCESS'
export const USUARIO_ATUALIZA_PERFIL_FAIL = 'USUARIO_ATUALIZA_PERFIL_FAIL'
export const USUARIO_ATUALIZA_PERFIL_RESET = 'USUARIO_ATUALIZA_PERFIL_RESET'
