export const USUARIO_LOGIN_REQUEST = 'USUARIO_LOGIN_REQUEST'
export const USUARIO_LOGIN_SUCCESS = 'USUARIO_LOGIN_SUCCESS'
export const USUARIO_LOGIN_FAIL = 'USUARIO_LOGIN_FAIL'

export const USUARIO_LOGOUT = 'USUARIO_LOGOUT'

export const USUARIO_REGISTRO_REQUEST = 'USUARIO_REGISTRO_REQUEST'
export const USUARIO_REGISTRO_SUCCESS = 'USUARIO_REGISTRO_SUCCESS'
export const USUARIO_REGISTRO_FAIL = 'USUARIO_REGISTRO_FAIL'

export const USUARIO_DETALHES_REQUEST = 'USUARIO_DETALHES_REQUEST'
export const USUARIO_DETALHES_SUCCESS = 'USUARIO_DETALHES_SUCCESS'
export const USUARIO_DETALHES_FAIL = 'USUARIO_DETALHES_FAIL'
export const USUARIO_DETALHES_RESET = 'USUARIO_DETALHES_RESET'


export const USUARIO_ATUALIZA_PERFIL_REQUEST = 'USUARIO_ATUALIZA_PERFIL_REQUEST'
export const USUARIO_ATUALIZA_PERFIL_SUCCESS = 'USUARIO_ATUALIZA_PERFIL_SUCCESS'
export const USUARIO_ATUALIZA_PERFIL_FAIL = 'USUARIO_ATUALIZA_PERFIL_FAIL'
export const USUARIO_ATUALIZA_PERFIL_RESET = 'USUARIO_ATUALIZA_PERFIL_RESET'

export const USUARIO_LISTAR_REQUEST = 'USUARIO_LISTAR_REQUEST'
export const USUARIO_LISTAR_SUCCESS = 'USUARIO_LISTAR_SUCCESS'
export const USUARIO_LISTAR_FAIL = 'USUARIO_LISTAR_FAIL'
export const USUARIO_LISTAR_RESET = 'USUARIO_LISTAR_RESET'

export const USUARIO_APAGAR_REQUEST = 'USUARIO_APAGAR_REQUEST'
export const USUARIO_APAGAR_SUCCESS = 'USUARIO_APAGAR_SUCCESS'
export const USUARIO_APAGAR_FAIL = 'USUARIO_APAGAR_FAIL'

export const USUARIO_ATUALIZAR_REQUEST = 'USUARIO_ATUALIZAR_REQUEST'
export const USUARIO_ATUALIZAR_SUCCESS = 'USUARIO_ATUALIZAR_SUCCESS'
export const USUARIO_ATUALIZAR_FAIL = 'USUARIO_ATUALIZAR_FAIL'
export const USUARIO_ATUALIZAR_RESET = 'USUARIO_ATUALIZAR_RESET'
