# Generated by Django 3.1.7 on 2021-02-21 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('marca', models.CharField(blank=True, max_length=200, null=True)),
                ('categoria', models.CharField(blank=True, max_length=200, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('avaliacao', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('num_avaliacoes', models.IntegerField(blank=True, default=0, null=True)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('num_estoque', models.IntegerField(blank=True, default=0, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('metodo_pagamento', models.CharField(blank=True, max_length=200, null=True)),
                ('imposto', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('frete', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('preco_total', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('status_pagamento', models.BooleanField(default=False)),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
                ('status_entrega', models.BooleanField(default=False)),
                ('data_entrega', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('quantidade', models.IntegerField(blank=True, default=0, null=True)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('imagem', models.CharField(blank=True, max_length=200, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.pedido')),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.produto')),
            ],
        ),
        migrations.CreateModel(
            name='EnderecoEntrega',
            fields=[
                ('endereco', models.CharField(blank=True, max_length=200, null=True)),
                ('cidade', models.CharField(blank=True, max_length=200, null=True)),
                ('cep', models.CharField(blank=True, max_length=200, null=True)),
                ('pais', models.CharField(blank=True, max_length=200, null=True)),
                ('frete', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('pedido', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Analise',
            fields=[
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('avaliacao', models.IntegerField(blank=True, default=0, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.produto')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
