# Generated by Django 3.1.7 on 2021-02-25 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_produto_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='metodo_pagamento',
            new_name='metodoPagamento',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='preco_total',
            new_name='precoTotal',
        ),
    ]
