# Generated by Django 3.1.7 on 2021-02-25 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210225_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='status_entrega',
            new_name='status_entregue',
        ),
    ]
