# Generated by Django 3.1.7 on 2021-03-02 19:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20210301_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='analise',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
