const produtos = [
    {
    '_id': '1',
    'nome': 'Notebook gamer Acer',
    'imagem': '/images/notebook.jpg',
    'descricao': 'Notebook top de linha pronto para atender seus requisitos gamer',
    'marca': 'Acer',
    'categoria': 'Informática',
    'preco': 5000.00,
    'estoque': 50,
    'avaliacao': 5,
    'num_avaliacao': 528,
    },
    {
    '_id': '2',
    'nome': 'Havaina de pedra',
    'imagem': '/images/chinelo.jpg',
    'descricao': 'O chinelo com durabilidade melhor que muita jóia',
    'marca': 'Havainas',
    'categoria': 'Casa',
    'preco': 15.0,
    'estoque': 0,
    'avaliacao': 4.5,
    'num_avaliacao': 152,
    },
    {
    '_id': '3',
    'nome': 'Fone de ouvido',
    'imagem': '/images/airpods.jpg',
    'descricao': 'Fone de ouvido de altíssima qualidade pronto para ter uma imersão única',
    'marca': 'Apple',
    'categoria': 'Acessórios',
    'preco': 220.99,
    'estoque': 12,
    'avaliacao': 4.0,
    'num_avaliacao': 62,
    },
    {
    '_id': '4',
    'nome': 'Playstation 4',
    'imagem': '/images/ps4.jpg',
    'descricao': 'Console de video game de última geração rodando jogos em qualidade jamais vista',
    'marca': 'Sony',
    'categoria': 'Jogos',
    'preco': 7500.00,
    'estoque': 10,
    'avaliacao': 4.00,
    'num_avaliacao': 2122,
    },
    {
    '_id': '5',
    'nome': 'Tv Samsung 8k',
    'imagem': '/images/tv.jpg',
    'descricao': 'Tv de 8k qualidade pronta para resoluções jamais experimentadas',
    'marca': 'Samsung',
    'categoria': 'TV',
    'preco': 1500.00,
    'estoque': 12,
    'avaliacao': 3.2,
    'num_avaliacao': '5',
    },
]

export default produtos